### ISSUE TITLE
File picker is missing bookmarks and network mounts

### ISSUE THREAD

**Issue by megamaced** [flathub/chat.rocket.RocketChat#11]
If I choose Add files from Computer this opens the GNOME file picker, but the file picker does not list any GVFS network mounts or bookmarks in the Other Locations area. If I use the regular RPM based install then I see those locations in the file picker

**Comment by andrevmatos** [comment]
Seems like Electron inside flatpak uses gtk2 file chooser instead of `GtkFileChooserNative`: https://github.com/electron/electron/issues/2911
https://github.com/electron/electron/pull/15293
@TingPing are you aware of any way to make Electron+Flatpak use portal file picker instead of native one? Couldn't find any docs on this.

**Comment by andrevmatos** [comment]
Things are a little bit better now, as I started exposing `home` (`xdg-download` wasn't being properly picked by electron somehow), so at least home and down, you'll get the folder there, but bookmarks and mounts will need to wait on above issues or a way to LD_PRELOAD xdg-portals on flatpaks.

**Comment by andrevmatos** [comment]
Fixed by #86
